#!/bin/sh

rm -rf [1-9]* log logs sets surfaces
rm -f constant/polyMesh/boundary
rm -f constant/polyMesh/faces
rm -f constant/polyMesh/neighbour
rm -f constant/polyMesh/owner
rm -f constant/polyMesh/points
rm -rf constant/polyMesh/sets
rm -f log.*
