#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="simpleFoam"

runApplication blockMesh

runApplication $application

runApplication wallShearStress -noZero -latestTime

runApplication foamLog log.$application

runApplication sample -latestTime
